### PR TITLE
feat: create notebook that publishes collection and item ingest for most collections

### PR DESCRIPTION
**Pull request by botanical**
### Changes
This notebook is based off of the reconciliation notebook but has been updated to:
- not merge summaries and retain external links
- point to MCP test and production
- exclude 
```
hls-l30-002-ej-reprocessed
hls-s30-002-ej-reprocessed
ls8-covid-19-example-data
landsat-c2l2-sr-antarctic-glaciers-pine-island
landsat-c2l2-sr-lakes-aral-sea
landsat-c2l2-sr-lakes-tonle-sap
landsat-c2l2-sr-lakes-lake-balaton
landsat-c2l2-sr-lakes-vanern
landsat-c2l2-sr-antarctic-glaciers-thwaites
landsat-c2l2-sr-lakes-lake-biwa
combined_CMIP6_daily_GISS-E2-1-G_tas_kerchunk_DEMO
```

### CODE REVIEW

**Comment by smohiudd** [comment]
Just confirming that these endpoints are from MCP `test` and `prod`?

```
if testing_mode:
    STAC_INGESTOR_API = "https://soltgnljhh.execute-api.us-west-2.amazonaws.com/"
    VEDA_STAC_API = "https://e9xlhyjfhk.execute-api.us-west-2.amazonaws.com/"
else:
    STAC_INGESTOR_API = "https://gh9ge13dej.execute-api.us-west-2.amazonaws.com/"
    VEDA_STAC_API = "https://6ouvl5o466.execute-api.us-west-2.amazonaws.com/"

```

**Comment by smohiudd** [comment]
In the last cell why is are you getting the collection?
```
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        json_response = response.json()
```

**Comment by botanical** [comment]
> In the last cell why is are you getting the collection?
> 
> ```
>         response = requests.get(url, headers=headers)
>         response.raise_for_status()
>         json_response = response.json()
> ```

Ooh nice catch @smohiudd ! That was remnant code from the other notebook. Let me remove that bit.

**Comment by botanical** [comment]
> Just confirming that these endpoints are from MCP `test` and `prod`?
> 
> ```
> if testing_mode:
>     STAC_INGESTOR_API = "https://soltgnljhh.execute-api.us-west-2.amazonaws.com/"
>     VEDA_STAC_API = "https://e9xlhyjfhk.execute-api.us-west-2.amazonaws.com/"
> else:
>     STAC_INGESTOR_API = "https://gh9ge13dej.execute-api.us-west-2.amazonaws.com/"
>     VEDA_STAC_API = "https://6ouvl5o466.execute-api.us-west-2.amazonaws.com/"
> ```

These are the test and prod endpoints but I can also use their domains if you prefer @smohiudd

**Comment by smohiudd** [comment]
Domains are just easier to distinguish but not a big deal.

**Review by smohiudd — APPROVED** [review]

**Pull request merged**
